version: "3.7"
services:
  gamification:
    image: "gamificationdev"
    container_name: gamification-integrated
    volumes:
      - .:/app
    env_file:
      - .env
      - .secrets
    environment:
      - PROTOCOL=http://
      - SERVER_NAME=${DOMAIN?Variable not set}
      - PORT=${PORT}
      - BASE_PATH=/gamification
      - MONGODB_URL=mongodb://user:userpass@mongodb:27017/data?retryWrites=true&w=majority
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not
        set}-gamification-http.rule=PathPrefix(`/gamification`)
      - traefik.http.services.${STACK_NAME?Variable not
        set}-gamification.loadbalancer.server.port=${PORT}
    networks:
      - traefik-public
    extra_hosts:
      - "auth1.localhost:172.17.0.1"
networks:
  traefik-public:
    external: true
